-- DATABASE SETUP UNTUK APLIKASI MANAJEMEN KOPERASI

-- 1. Buat Database
CREATE DATABASE IF NOT EXISTS db_koperasi;
USE db_koperasi;

-- 2. Buat Tabel Anggota
CREATE TABLE IF NOT EXISTS anggota (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    alamat VARCHAR(200) NOT NULL,
    telepon VARCHAR(15) NOT NULL,
    simpanan_awal DOUBLE NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
